"""questions update

Revision ID: eb7ef2e326bb
Revises: eebe0e2054b9
Create Date: 2024-11-06 18:31:12.730709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7ef2e326bb'
down_revision: Union[str, None] = 'eebe0e2054b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_questions', sa.Column('test_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'test_questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_column('test_questions', 'test_id')
    # ### end Alembic commands ###
